string sum;
Console.WriteLine("What is the sum of investment?");
double vklad = Convert.ToInt32(Console.ReadLine());
double aksia1 = vklad * 8 / 100;
double aksia2 = vklad * 95 / 1000;
double aksia3 = vklad * 10 / 100;
Console.WriteLine(aksia1);
Console.WriteLine(aksia2);
Console.WriteLine(aksia3);
Console.WriteLine(aksia3);